# spec file for repeated training on data forced by CESM2 future (2075-2100) projection using NN modularEB (=without precipitation)

directories:
  source_dir: data/processed/HIRHAM5-CESM2/future
  base_dir: data/processed/crossval/v_01
  data_file: CESM2future_meltNN_trainval
  out_dir: output/repeated_CESM2future_modularNNEB_log
  overwrite: false
  temp_split_file: train_val_split_future_100.json
  spatial_sub_file: GRL_subsampleidx_future_5000_flattened.zarr
  zones_file: GRLzones.zarr

data:
  input:
  - energyin
  - dswrad
  - energyin_10yr-avg
  - dswrad_10yr-avg
  prec_days: 9
  target:
  - snmel



model:
  hidden_activation: LeakyReLU
  layers_daily_feat_extractor:
  - 128
  - 128
  - 128
  layers_medrange_feat_extractor: null
  layers_regressor:
  - 160
  - 128
  - 128
  - 64
  layers_spinup_feat_extractor:
  - 32
  - 32
  output_activation: ""
  use_season: true

training:
  restarts: 20
  batch_size: 512
  continue_training: false
  epochs: 300
  loss_reg: mse
  lr: 0.03
  lr_decay: 0.9
  lr_decay_epochs: 50
  optimizer: adam