# spec file for joint training from ERA-Interim and future CESM2 data
# run combine_zarr_sets.py beforehand to create ERAI_CESM2future_meltNN/data_sub.zarr

directories:
  source_dir: data/processed/crossval/v_01
  base_dir: data/processed/crossval/v_01
  data_file: ERAI_CESM2future_meltNN
  out_dir: output/repeated_ERAICESM2future_2500_modularNNEBM
  overwrite: false
  temp_sub_file: temp_subsample_100_histandfuture.json
  spatial_sub_file: GRL_subsampleidx_2500_flattened.zarr
  zones_file: GRLzones.zarr

data:
  input:
  - rainfall
  - snfall
  - energyin
  - dswrad
  - rainfall_10yr-avg
  - snfall_10yr-avg
  - energyin_10yr-avg
  - dswrad_10yr-avg
  prec_days: 9
  target:
  - snmel
  transform_inputs:
    rainfall: [log,1]
    snfall: [log,1]
    rainfall_10yr-avg: [log,1]
    snfall_10yr-avg: [log,1]


model:
  hidden_activation: LeakyReLU
  layers_daily_feat_extractor:
  - 128
  - 128
  - 256
  layers_medrange_feat_extractor: null
  layers_regressor:
  - 256
  - 128
  - 64
  - 32
  - 16
  layers_spinup_feat_extractor:
  - 32
  - 32
  output_activation: ""
  use_season: true

training:
  restarts: 20
  batch_size: 256
  continue_training: false
  epochs: 300
  loss_reg: mse
  lr: 0.03
  lr_decay: 0.9
  lr_decay_epochs: 50
  optimizer: adam
